package com.azureoauth.azureoauthhandlerservice.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.azureoauth.azureoauthhandlerservice.AzureOAuthHandlerService;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;

/**
 * Controller object for domain model class {@link AzureOAuthHandlerService}.
 * @see AzureOAuthHandlerService
 */
@RestController
@Api(value = "AzureOauthHandlerController", description = "controller class for java service execution")
@RequestMapping("/azureOAuthHandler")
public class AzureOauthHandlerController {

    @Autowired
    private AzureOAuthHandlerService azureOAuthHandlerService;

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @RequestMapping(value = "/callback", method = RequestMethod.GET)
    public void callback( HttpServletRequest request,  HttpServletResponse response) throws ServletException {
        azureOAuthHandlerService.callback(request, response);
    }

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @RequestMapping(value = "/accessToken", method = RequestMethod.GET)
    public String getAccessToken( HttpServletRequest request) throws ServletException {
        return azureOAuthHandlerService.getAccessToken(request);
    }

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @RequestMapping(value = "/callbackURL", method = RequestMethod.GET)
    public String getCallbackURL( HttpServletRequest request) {
        return azureOAuthHandlerService.getCallbackURL(request);
    }

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @RequestMapping(value = "/loginURl", method = RequestMethod.GET)
    public String getLoginURL( HttpServletRequest request, @RequestParam(value = "state", required = false) String state) {
        return azureOAuthHandlerService.getLoginURL(request, state);
    }
}

